baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "ThuanSB & his daily risks"
author = "thuansb"
copyright = "Copyright (c) 2016, ThuanSB; all rights reserved."
canonifyurls = true
paginate = 3

[params]
  disqusShortname = "your disqus id." # optional
  toc = true # optional, When set to TRUE this parameter, table of contents appears in all articles.
